// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpba4RbZJeuPxruLQP3NPsMYd1VYY_O7o',
    appId: '1:365453936537:web:511b120bfe8e2f87e27508',
    messagingSenderId: '365453936537',
    projectId: 'ty-makeup',
    authDomain: 'ty-makeup.firebaseapp.com',
    databaseURL: 'https://ty-makeup-default-rtdb.firebaseio.com',
    storageBucket: 'ty-makeup.firebasestorage.app',
    measurementId: 'G-EGKJXK60XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAswmifT6gvnflp04vfJhNCGH1_i7aW4Xw',
    appId: '1:365453936537:android:6156e0f9d4fb531be27508',
    messagingSenderId: '365453936537',
    projectId: 'ty-makeup',
    databaseURL: 'https://ty-makeup-default-rtdb.firebaseio.com',
    storageBucket: 'ty-makeup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-veA7926ytRpP_QgosXHSNj4tPwWpAfg',
    appId: '1:365453936537:ios:befc25f6b708fcbee27508',
    messagingSenderId: '365453936537',
    projectId: 'ty-makeup',
    databaseURL: 'https://ty-makeup-default-rtdb.firebaseio.com',
    storageBucket: 'ty-makeup.firebasestorage.app',
    iosBundleId: 'com.example.dashboardTymakeup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-veA7926ytRpP_QgosXHSNj4tPwWpAfg',
    appId: '1:365453936537:ios:befc25f6b708fcbee27508',
    messagingSenderId: '365453936537',
    projectId: 'ty-makeup',
    databaseURL: 'https://ty-makeup-default-rtdb.firebaseio.com',
    storageBucket: 'ty-makeup.firebasestorage.app',
    iosBundleId: 'com.example.dashboardTymakeup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpba4RbZJeuPxruLQP3NPsMYd1VYY_O7o',
    appId: '1:365453936537:web:f29cb17c2f26d30ce27508',
    messagingSenderId: '365453936537',
    projectId: 'ty-makeup',
    authDomain: 'ty-makeup.firebaseapp.com',
    databaseURL: 'https://ty-makeup-default-rtdb.firebaseio.com',
    storageBucket: 'ty-makeup.firebasestorage.app',
    measurementId: 'G-5PME7FCQF9',
  );
}
